version: '3.7'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    volumes:
      - db_data:/data

volumes:
  db_data:
